"""empty message

Revision ID: 3867a9a57b7e
Revises: 
Create Date: 2020-06-19 21:58:41.977451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3867a9a57b7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strains',
    sa.Column('strain_id', sa.Integer(), nullable=False),
    sa.Column('strain', sa.String(length=128), nullable=True),
    sa.Column('strain_type', sa.String(length=128), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('effects', sa.String(length=128), nullable=True),
    sa.Column('flavor', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('strain_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strains')
    # ### end Alembic commands ###
